name: baidumusic
version: 1

libraries:
- name: django
  version: 1.5

handlers:
- url: /favicon.ico
  static_path: static/img/favicon.ico
- url: /image/
  static_path: static/img
- url: /css/
  static_path: static/css
- url: /js/
  static_path: static/js
- url: /fonts/
  static_path: static/fonts
